version: "3.9"

services:
  drupal:
    build: .
    container_name: driftcore-sandbox
    ports:
      - "8081:80"
    environment:
      DRUPAL_DB_HOST: database
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal
    volumes:
      - drupal-config:/var/www/html/config
    depends_on:
      - database

  database:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

volumes:
  drupal-config:
  db-data:
